In [ ]:
from sklearn.datasets import load_iris

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [ ]:
iris_data

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [ ]:
# feature 2차원  target 1차원 + label을 붙여줘야한다.


In [ ]:
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
iris_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris_data.data.shape # 150개의 문제 4개의 컬럼


(150, 4)

In [ ]:
# 데이터 프레임에 넣어라.
# 데이터 ,컬럼명

df=pd.DataFrame(iris_data.data, columns= iris_data.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
df['target'] =iris_data.target
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [ ]:
df.columns=['sepal length','sepal width','petal length','petal width','targer']
df

sepal length  sepal width  petal length  petal width  targer
0             5.1          3.5           1.4          0.2       0
1             4.9          3.0           1.4          0.2       0
2             4.7          3.2           1.3          0.2       0
3             4.6          3.1           1.5          0.2       0
4             5.0          3.6           1.4          0.2       0
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[150 rows x 5 columns]

In [ ]:
# 공부할 데이터와 테스트용 데이터를 분리
from sklearn.model_selection import  train_test_split

In [ ]:
X_data =df.loc[:,'sepal length':'petal length'] # 문제데이터
y_data =df.loc[:,'targer'] #정답데이터

In [ ]:
# 문제는 대문자 정답은 소문자
X_train, X_test , y_train ,y_test = train_test_split( # 파라미터들
    X_data, # 문제 데이터
    y_data,  # 답데이터
    test_size = 0.2, # 비율
    shuffle =True, # 셔플링여부
    random_state =20 # 시드값
) 

In [ ]:
X_train, X_test , y_train ,y_test

(     sepal length  sepal width  petal length
 95            5.7          3.0           4.2
 88            5.6          3.0           4.1
 0             5.1          3.5           1.4
 46            5.1          3.8           1.6
 11            4.8          3.4           1.6
 ..            ...          ...           ...
 22            4.6          3.6           1.0
 75            6.6          3.0           4.4
 137           6.4          3.1           5.5
 15            5.7          4.4           1.5
 99            5.7          2.8           4.1
 
 [120 rows x 3 columns],      sepal length  sepal width  petal length
 47            4.6          3.2           1.4
 73            6.1          2.8           4.7
 74            6.4          2.9           4.3
 129           7.2          3.0           5.8
 67            5.8          2.7           4.1
 89            5.5          2.5           4.0
 143           6.8          3.2           5.9
 21            5.1          3.7           1.5
 108    

In [ ]:
X_train.shape

(120, 3)

In [ ]:
X_test.shape

(30, 3)

In [ ]:
y_train.shape

(120,)

In [ ]:
y_test.shape

(30,)

In [ ]:
# 공부방법론을 정해서 공부시키자.
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn= KNeighborsClassifier(n_neighbors= 3) #n_neighbors 어디까지 유사도로볼껀지에대한 코드 / 하이퍼파라메터 (내가조절할수있는 파라메터!)

In [ ]:
knn.fit(X_train,y_train) # 공부하라는 코드

KNeighborsClassifier(n_neighbors=1)

In [ ]:
# 테스트용 데이터로 점수가 얼마나 나오는지 검증해보자.
pred  = knn.predict(X_test)
pred

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 2, 1, 1, 0, 2, 2])

In [ ]:
#모의고사 점수가 얼마가 나왔는지 확인을 해보자 => 채점
from sklearn.metrics import accuracy_score

In [ ]:
jum =  accuracy_score(y_test,pred) # 원래정답, 내가푼답 

jum # accuracy

0.9666666666666667

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc= SVC(kernel='rbf')

In [ ]:
svc.fit(X_train,y_train)

SVC()

In [ ]:
pred2  = svc.predict(X_test)
pred2

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 1, 1, 1, 0, 2, 2])

In [ ]:
jum2 =  accuracy_score(y_test,pred2) # 원래정답, 내가푼답 

jum2 # accuracy

1.0