In [ ]:
from sklearn.datasets import load_wine

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
win_data = load_wine()
win_data

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [ ]:
win_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [ ]:
win_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
win_data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [ ]:
win_data.data.shape

(178, 13)

In [ ]:
df= pd.DataFrame(win_data.data , columns= win_data.feature_names)
df

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [ ]:
df['target'] = win_data.target
df

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0      14.23        1.71  2.43  ...                          3.92   1065.0       0
1      13.20        1.78  2.14  ...                          3.40   1050.0       0
2      13.16        2.36  2.67  ...                          3.17   1185.0       0
3      14.37        1.95  2.50  ...                          3.45   1480.0       0
4      13.24        2.59  2.87  ...                          2.93    735.0       0
..       ...         ...   ...  ...                           ...      ...     ...
173    13.71        5.65  2.45  ...                          1.74    740.0       2
174    13.40        3.91  2.48  ...                          1.56    750.0       2
175    13.27        4.28  2.26  ...                          1.56    835.0       2
176    13.17        2.59  2.37  ...                          1.62    840.0       2
177    14.13        4.10  2.74  ...                          1.60    560.0       2

[178 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_data =df.loc[:,'alcohol':'proline']
y_data =df.loc[:,'target']

In [ ]:
X_train, X_test , y_train ,y_test = train_test_split( # 파라미터들
    X_data, # 문제 데이터
    y_data,  # 답데이터
    test_size = 0.2, # 비율
    shuffle =True, # 셔플링여부
    random_state =20 # 시드값
) 

In [ ]:
X_train.shape

(142, 13)

In [ ]:
X_test.shape

(36, 13)

In [ ]:
y_train.shape

(142,)

In [ ]:
y_test.shape

(36,)

In [ ]:
# 공부방법론을 정해서 공부시키자.
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn= KNeighborsClassifier(n_neighbors= 16) # 이거이후로 안올라감

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=16)

In [ ]:
pred  = knn.predict(X_test)
pred

array([1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 0, 1, 2, 2, 0, 1, 2, 0, 0, 2, 2, 0,
       1, 0, 2, 1, 0, 2, 1, 1, 2, 2, 1, 2, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
jum =  accuracy_score(y_test,pred) # 원래정답, 내가푼답 

jum # accuracy

0.75

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc= SVC(kernel='rbf') # rbf :  Radial basis Function 방사형 구조

In [ ]:
svc.fit(X_train,y_train)

SVC()

In [ ]:
pred2  = svc.predict(X_test)
pred2

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0,
       1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 2, 0, 0])

In [ ]:
jum2 =  accuracy_score(y_test,pred2) # 원래정답, 내가푼답 

jum2 # accuracy

0.7222222222222222